### ISSUE TITLE
[Suggestion] Change dependencies to git submodule

### ISSUE THREAD

**Issue by andrefmsilva** [kingslay/FFmpegKit#19]
@karelrooted  has a fork where all dependencies are all git submodules. 
I've tried it and it really helps a lot because we can check all latest commits for each dependency and makes it easier to apply/create custom patch.

Another things to make this more generic is to auto apply patches from folders with lib name.
- we add patch files to lib folder
- the script finds all patch for that lib
- sort them by name (so we can use patterns like 0001-patch_name.patch)
- git reset and then apply them in order on builder init

**Comment by andrefmsilva** [comment]
something like this:
https://github.com/karelrooted/libmpv/tree/main/Sources/MPVBuild/patch

**Comment by karelrooted** [comment]
Xcode has problems with large submodule(did a quick search, didn't find a depth or shadow submodule switch),that's one of the reason I split the project to two repo

When import large submodule package, Xcode will use a very long time to load the package, so much so that user will likely cancel it...

We can change binary framework to url though, that way ffmpegkit is not directly imported in Xcode

```
.binaryTarget(
            name: "Libass",
            url: "https://github.com/kingslay/ffmpegkit/releases/download/v0.0.1-alpha/Libass.xcframework.zip",
            checksum: "777136ad86cfcdd8f53ce90697d16121111b379269a3f794830e2b88b700f220"
)
```

I use a 2018 MacBook Pro 15inch, sometimes is helpful to set breakpoint in the c library code, but if the code is included in the package, Xcode hangs very frequently..., so currently i import the package include the code only when necessary, Xcode really is the worst ide in the world :-)

**Comment by kingslay** [comment]
虽然不能用submodule。但是你提的关于patch 自动处理的提议很好。这个是可以实现的。
